version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocyclo
    - ineffassign
    - unconvert
    - dupl
  disable-all: false
   
issues:
  exclude-use-default: false