version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - gocyclo
    - ineffassign
    - unconvert
    - dupl
  disable-all: false
  exclusions:
    rules:
      - path: '(.+)_test\.go$'
        linters:
          - errcheck
